### ISSUE TITLE
Containerize the project

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/fastapi-heroku#2]
Construct Dockerfile and docker-compose.yml

**Comment by RishiKumarRay** [comment]
I would like to do this please assign me

**Comment by sadikkuzu** [comment]
Thanks @RishiKumarRay 👍🏼

**Comment by RishiKumarRay** [comment]
@sadikkuzu can you please tell me what are the steps of running the project locally

**Comment by sadikkuzu** [comment]
On `python:latest`

```sh
pip install -qUr requirements.txt
uvicorn main:app
```

**Comment by RishiKumarRay** [comment]
@sadikkuzu please review the PR #3 i have added everything as you mentioned
